In [1]:
import pandas as pd

In [2]:
df_votants = pd.read_csv('database_deputes.csv', index_col=0)
df_votes = pd.read_csv('database_votes2.csv', index_col=0)

In [327]:
df_votes = df_votes.set_index('idVotant')

In [328]:
df_age = df_votes[['Nom', 'Prénom', 'date_naissance']]
df_age = df_age.drop_duplicates()

In [329]:
df_age['wikilink'] = df_age['Prénom']+'_'+df_age['Nom']

In [330]:
df_age

               Nom       Prénom date_naissance          wikilink
idVotant
PA606171   Ferrand      Richard     1962-07-01   Richard_Ferrand
PA721824    Renson       Hugues            NaN     Hugues_Renson
PA719952       Mis  Jean-Michel            NaN   Jean-Michel_Mis
PA607395   Travert     Stéphane     1969-10-12  Stéphane_Travert
PA718710     Boyer      Pascale            NaN     Pascale_Boyer
...            ...          ...            ...               ...
PA643192   Jourdan      Chantal            NaN   Chantal_Jourdan
PA721768     Silin        Marie            NaN       Marie_Silin
PA774962     Lebon       Karine            NaN      Karine_Lebon
PA721666  Audibert        Edith            NaN    Edith_Audibert
PA720802     Pujol    Catherine            NaN   Catherine_Pujol

[575 rows x 4 columns]

In [331]:
#correction des liens wiki
df_age.loc['PA718802', 'wikilink'] = 'Alain_Péréa'
df_age.loc['PA722170', 'wikilink'] = 'Sophie_Beaudouin-Hubière'
df_age.loc['PA267780', 'wikilink'] = 'Agnès_Firmin-Le_Bodo'
df_age.loc['PA718850', 'wikilink'] = 'Pierre_Cordier_(homme_politique)'
df_age.loc['PA719138', 'wikilink'] = 'Michel_Castellani_(homme_politique)'
df_age.loc['PA720394', 'wikilink'] = 'Nicole_Gries-Trisse'
df_age.loc['PA720590', 'wikilink'] = 'Benoît_Potterie'
df_age.loc['PA722178', 'wikilink'] = 'Jacques_Maire_(homme_politique)'
df_age.loc['PA721182', 'wikilink'] = 'Frédéric_Petit_(homme_politique,_1961)'
df_age.loc['PA719592', 'wikilink'] = 'Benoît_Simian'
df_age.loc['PA720138', 'wikilink'] = 'Laëtitia_Saint-Paul'
df_age.loc['PA609332', 'wikilink'] = 'Olivier_Faure_(homme_politique)'
df_age.loc['PA720696', 'wikilink'] = 'Béatrice_Descamps_(femme_politique,_1961)'
df_age.loc['PA719480', 'wikilink'] = 'Olivier_Gaillard_(homme_politique)'
df_age.loc['PA421348', 'wikilink'] = 'André_Villiers_(homme_politique)'
df_age.loc['PA720932', 'wikilink'] = 'Dominique_Da_Silva_(homme_politique)'
df_age.loc['PA718768', 'wikilink'] = 'Alexandra_Valetta-Ardisson'
df_age.loc['PA1008', 'wikilink'] = 'Alain_David_(homme_politique)'
df_age.loc['PA1809', 'wikilink'] = 'Jérôme_Lambert_(homme_politique)'
df_age.loc['PA267042', 'wikilink'] = 'Yannick_Favennec_Becot'
df_age.loc['PA607090', 'wikilink'] = 'Jean-Pierre_Vigier_(homme_politique)'
df_age.loc['PA722280', 'wikilink'] = 'Philippe_Meyer_(homme_politique)'
df_age.loc['PA642724', 'wikilink'] = 'Frédéric_Barbier_(homme_politique)'
df_age.loc['PA721538', 'wikilink'] = 'Muriel_Roques-Étienne'
df_age.loc['PA720802', 'wikilink'] = 'Catherine_Pujol_(femme_politique)'

In [332]:
import urllib
import bs4
import pandas as pd
from urllib.request import Request, urlopen
from urllib import request, parse
import ssl
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt

liste_age = []

for k in df_age.index:
    context = ssl._create_unverified_context()
    url = 'https://fr.wikipedia.org/'
    path = parse.quote('wiki/' + df_age.loc[k]['wikilink'])
    req = Request(url+path, headers = {'User-Agent': 'Chrome/5.0'})
    webpage = urlopen(req).read() 
    page = bs4.BeautifulSoup(webpage, "lxml")
    age = page.find('span',{'class':'noprint'}).text.strip()[1:3]
    liste_age.append(age)

In [333]:
len(liste_age)

575

In [334]:
df_age['age'] = liste_age

In [335]:
df_age

,Nom,Prénom,date_naissance,wikilink,age
idVotant,,,,,
PA606171,Ferrand,Richard,1962-07-01,Richard_Ferrand,58
PA721824,Renson,Hugues,NaN,Hugues_Renson,42
PA719952,Mis,Jean-Michel,NaN,Jean-Michel_Mis,53
PA607395,Travert,Stéphane,1969-10-12,Stéphane_Travert,51
PA718710,Boyer,Pascale,NaN,Pascale_Boyer,55
...,...,...,...,...,...
PA643192,Jourdan,Chantal,NaN,Chantal_Jourdan,62
PA721768,Silin,Marie,NaN,Marie_Silin,42
PA774962,Lebon,Karine,NaN,Karine_Lebon,35
PA721666,Audibert,Edith,NaN,Edith_Audibert,72
PA720802,Pujol,Catherine,NaN,Catherine_Pujol_(femme_politique),60

In [340]:
df_age.to_csv('age.csv',index=True)